# I (the author) normally run this script from the console, which requires setting the local path.
# This command is aliased in my environment to select the correct absolute working directory.
# Replace it with a command to select REPO_ROOT/subsequentAnalysis on your system
cdreds()

source("./prep_and_data_reading.R")
source("./habitat_cover_table_functions.R")
source("./model_making_and_loco_cross_validation.R")
source("./prediction_metric_functions.R")
source("./leave_one_cluster_out_plot_routines.R")
source("./consistency_plot_functions.R")
source("./map_figure_system.R")

models_dir <- "../fullProofOfConcept/savedModels/"
new_models_dir <- "./new_models/"

formStandard <- sparrow ~ hedge + grass + tree + roof + artif + bushAndCult + anDistHdg + anDistRf + ( 1 | id ) +
  ( 0 + hedge + grass + tree + roof + artif + bushAndCult + anDistHdg + anDistRf || id )

pred_names <- c( "hedge", "grass", "tree", "roof", "artif", "bushAndCult", "anDistHdg", "anDistRf" )

runSlowModels <- FALSE # Otherwise you will wait a long time

# Only the authors can have process_raw_GA_data set to true, because the original Garden Advice celling data
# cannot be shared in original format for reasons of privacy
process_raw_GA_data <- FALSE

###### Read data #############################################################################

# Read new (GA) data
if( process_raw_GA_data ) {
  dFRaw <- process_files_in_order()
  output_coords(dFRaw)
  cat("REDS_ONE batches contain", nrow(dFRaw), "rows and", ncol(dFRaw), "columns\n")
  cat("Number of unique batches:", length(unique(dFRaw$batch)), "\n")
  cat("Number of unique gardens:", length(unique(dFRaw$garden.guid)), "\n")
  cat("Gardens are:", unique(dFRaw$garden.guid), "\n")
  cat("Top left of data:\n")
  print(head(dFRaw[,1:4]))
  dF <- cellingToAnalysisFormat(dFRaw)
  write.csv(dF, "processed_GA_data.csv", row.names = FALSE)
} else {
  dF <- read.csv("processed_GA_data.csv")
}

# Read initial (GHSP) data
dFO <- readGlasgowData()
caseControlOffset <- -2.056832 # The original offset calculated using pilot data
dFOWithOriginalOffset <- transform(dFO, prevalenceOffset = caseControlOffset)
dFBothOriginalOffset <- merge_glasgow_with_REDS_data(dFO, dF, caseControlOffset )
glasgow_gardens <- unique(dFO$id)

finalSparrowPrevalence <- mean(tapply(dF$sparrow, dF$id, mean))
finalCaseControlOffset <- log( finalSparrowPrevalence / ( 1 - finalSparrowPrevalence) )
finalCaseControlOffset
dFBothFinalOffset <- merge_glasgow_with_REDS_data( dFO, dF, finalCaseControlOffset )
dFOWithFinalOffset <- transform( dFO, prevalenceOffset = finalCaseControlOffset )
dFWithFinalOffset <- transform( dF, prevalenceOffset = 0 )

##### Read or run slow MCMC models ######################################################################

# Read or run final model (final offset)
if( runSlowModels ) {
  modUpdatedDay5FinalOffset <- stan_glmer(formStandard, offset = prevalenceOffset, data = dFBothFinalOffset, family=binomial)
  saveRDS(modUpdatedDay5FinalOffset, file.path(new_models_dir,"modDay5FinalOffset.rds") )
} else {
  modUpdatedDay5FinalOffset <- readRDS(file.path(new_models_dir, "modDay5FinalOffset.rds") )
}

# Read or run Glasgow model (final offset)
if( runSlowModels ) {
  modGlasgowFinalOffset <- stan_glmer(formStandard, offset = prevalenceOffset, data = dFOWithFinalOffset, family=binomial )
  saveRDS(modGlasgowFinalOffset, file.path(new_models_dir, "modGlasgowFinalOffset.rds") )
} else {
  modGlasgowFinalOffset <- readRDS(file.path(new_models_dir, "modGlasgowFinalOffset.rds") )
}

########### Basic Garden descriptives ##################################################################

# Boundary is how much of a 4m^2 cell is inside the garden boundary, so this gives us garden sizes
boundary_sums <- aggregate(boundary ~ id, data = dF, FUN = sum)
boundary_sums$boundary <- boundary_sums$boundary * 4
summary(boundary_sums$boundary)

# The map is generated by the Python script plot_gardens.py
# The rural / urban information is generated by the Python script rural_urban_lookup.py

# Slightly kludgy: this function removes imputed hedge distances if you tell it which ones were imputed
summary_table <- create_habitat_summary_table(invertPrepDistancesForAnalysis(dFBothFinalOffset), dF$imputedDistHdg )
print(summary_table)

# Maximum hedge distance (imputed when hedges are missing from a garden)
max(invertPrepDistancesForAnalysis(dFBothFinalOffset)$distHdg)

########### Model parameter updating (also MCMC vs INLA) ###############################################

modGlasgowFinalOffset_INLA <- create_inla_model(dFOWithFinalOffset)
modBothFinalOffset_INLA <- create_inla_model(dFBothFinalOffset)

posteriorPlot <- plot_model_comparison(
  models = list( modGlasgowFinalOffset, modUpdatedDay5FinalOffset, modGlasgowFinalOffset_INLA, modBothFinalOffset_INLA ),
  model_types = c("MCMC", "MCMC", "INLA", "INLA" ),
  distribution_types = c("posterior", "posterior", "posterior", "posterior" ),
  model_names = c("GHSP only", "Updated with GA", "GHSP only", "Updated with GA" ),
  title = NULL,
  fill_colors = c(GHSP_blue, GA_orange, NA, NA ),
  line_colors = c(NA, NA, GHSP_blue, GA_orange ),
  save_plot = "posteriors_plot.png"
)
print(posteriorPlot)

# For the probabilities that posterior differences represent real differences
inla_compare_fixed_effects(modBothFinalOffset_INLA, modGlasgowFinalOffset_INLA, "grass", ci_level = 0.95)
inla_compare_fixed_effects(modBothFinalOffset_INLA, modGlasgowFinalOffset_INLA, "anDistRf", ci_level = 0.95)


############################ Leave one out, but INLA #################

# run_quickly <- FALSE runs the more complicated Bayesian model of change scores (that produces the credible intervals
# in figure 5) that was preregistered. It's slow because it uses every single data point rather than averaging over
# gardens (which is what run_quickly <- TRUE does). 
run_quickly <- FALSE
loco_output_dir <- "loco_results"

# "holdout" is using the standard INLA mechanisms for making predictions
prediction_method <- "holdout"

{ # Start a block just so code is not mixed with output in a ugly way when running on console
  if( runSlowModels ) {
    cat("Starting LOCO cross-validation comparison...\n")
    loco_cv_results <- run_loco_comparison(dFO, dF, finalCaseControlOffset,
                                           evaluate_all_data = TRUE,
                                           own_rolled_brier = TRUE,
                                           output_dir = loco_output_dir,
                                           prediction_method = prediction_method)
    cat("\nAnalyzing results...\n")
    cat("\n...predictions for all data...\n")
    analysis_results_all <- analyze_brier_comparison(loco_cv_results$brier_scores,
                                                      loco_cv_results$decomp_scores,
                                                      run_quickly = run_quickly)
    cat("\n...predictions for old data only...\n")
    analysis_results_old <- analyze_brier_comparison(
      loco_cv_results$brier_scores[loco_cv_results$brier_scores$garden %in% glasgow_gardens, ],
      loco_cv_results$decomp_scores[loco_cv_results$decomp_scores$garden %in% glasgow_gardens, ],
      run_quickly = run_quickly)

    cat("\n...predictions for new data only...\n")
    analysis_results_new <- analyze_brier_comparison(
      loco_cv_results$brier_scores[!(loco_cv_results$brier_scores$garden %in% glasgow_gardens), ],
      loco_cv_results$decomp_scores[!(loco_cv_results$decomp_scores$garden %in% glasgow_gardens), ],
      run_quickly = run_quickly)

    loco_results <- list(all = analysis_results_all,
                         old = analysis_results_old,
                         new = analysis_results_new,
                         full_results = loco_cv_results)

    saveRDS(loco_results, file.path(loco_output_dir, paste0("loco_analysis_", prediction_method, ".rds")))
  } else {
    loco_results <- readRDS(file.path(loco_output_dir, paste0("loco_analysis_", prediction_method, ".rds")))
  }
}

plot_loco( loco_results, glasgow_gardens = glasgow_gardens )


############################ Threshold-related prediction performance

# MCC as threshold

# Updated model, MCMC
optimalThresholdMCCUpdatedMCMC <- optimize_threshold( modUpdatedDay5FinalOffset, dFWithFinalOffset, offset = 0,
  metric = "mcc", model_type = "stan_glmer"  )
threshStatMCCUpdatedMCMC <- generate_cluster_prediction_summaries(modUpdatedDay5FinalOffset, dFWithFinalOffset, offset = 0,
                                                                  threshold = optimalThresholdMCCUpdatedMCMC, model_type = "stan_glmer" )

# Updated model, INLA
optimalThresholdMCCUpdatedINLA <- optimize_threshold(modBothFinalOffset_INLA, dFWithFinalOffset, offset = 0,
  metric = "mcc", model_type = "inla", original_data = dFBothFinalOffset )
threshStatMCCUpdatedINLA <- generate_cluster_prediction_summaries(modBothFinalOffset_INLA, dFWithFinalOffset, offset = 0,
                                                                  threshold = optimalThresholdMCCUpdatedINLA, model_type = "inla", original_data = dFBothFinalOffset )

# Original Glasgow model, MCMC
optimalThresholdMCCGlasgowMCMC <- optimize_threshold( modGlasgowFinalOffset, dFWithFinalOffset, offset=0,
  metric = "mcc", model_type = "stan_glmer" )
threshStatMCCGlasgowMCMC <- generate_cluster_prediction_summaries(modGlasgowFinalOffset, dFWithFinalOffset, offset=0,
                                                                  threshold = optimalThresholdMCCGlasgowMCMC, model_type = "stan_glmer" )

# Original Glasgow model, INLA
optimalThresholdMCCGlasgowINLA <- optimize_threshold( modGlasgowFinalOffset_INLA, dFWithFinalOffset, offset = 0,
  metric = "mcc", model_type = "inla", original_data = dFOWithOriginalOffset )
threshStatMCCGlasgowINLA <- generate_cluster_prediction_summaries(modGlasgowFinalOffset_INLA, dFWithFinalOffset, offset = 0,
                                                                  threshold = optimalThresholdMCCGlasgowINLA, model_type = "inla", original_data = dFOWithOriginalOffset )


# Prevalence threshold optimised

# Updated model, MCMC
optimalThresholdPrevUpdatedMCMC <- optimize_threshold( modUpdatedDay5FinalOffset, dFWithFinalOffset, offset = 0,
  metric = "prevalence", model_type = "stan_glmer", prevalence = finalSparrowPrevalence )
threshStatPrevUpdatedMCMC <- generate_cluster_prediction_summaries(modUpdatedDay5FinalOffset, dFWithFinalOffset, offset = 0,
                                                                   threshold = optimalThresholdPrevUpdatedMCMC, model_type = "stan_glmer" )

# Original Glasgow model, MCMC
optimalThresholdPrevGlasgowMCMC <- optimize_threshold( modGlasgowFinalOffset, dFWithFinalOffset, offset=0,
  metric = "prevalence", model_type = "stan_glmer", prevalence = finalSparrowPrevalence )
threshStatPrevGlasgowMCMC <- generate_cluster_prediction_summaries(modGlasgowFinalOffset, dFWithFinalOffset, offset=0,
                                                                   threshold = optimalThresholdPrevGlasgowMCMC, model_type = "stan_glmer" )

# Updated model, INLA
optimalThresholdPrevUpdatedINLA <- optimize_threshold( modBothFinalOffset_INLA, dFWithFinalOffset, offset = 0,
  metric = "prevalence", model_type = "inla", prevalence = finalSparrowPrevalence, original_data = dFBothFinalOffset )
threshStatPrevUpdatedINLA <- generate_cluster_prediction_summaries(modBothFinalOffset_INLA, dFWithFinalOffset, offset = 0,
                                                                   threshold = optimalThresholdPrevUpdatedINLA, model_type = "inla", original_data = dFBothFinalOffset )

# Original Glasgow model, INLA
optimalThresholdPrevGlasgowINLA <- optimize_threshold( modGlasgowFinalOffset_INLA, dFWithFinalOffset, offset=0,
  metric = "prevalence", model_type = "inla", prevalence = finalSparrowPrevalence, original_data = dFOWithOriginalOffset )
threshStatPrevGlasgowINLA <- generate_cluster_prediction_summaries(modGlasgowFinalOffset_INLA, dFWithFinalOffset, offset=0,
                                                                   threshold = optimalThresholdPrevGlasgowINLA, model_type = "inla", original_data = dFOWithOriginalOffset )


# Tables

# MCC, original vs updated, MCMC
create_model_comparison_table( threshStatMCCGlasgowMCMC, threshStatMCCUpdatedMCMC,
  "threshStatMCCOriginalVsUpdatedMCMC.tsv", metrics = c("plr","mcc") )

# MCC, original vs updated, INLA
create_model_comparison_table( threshStatMCCGlasgowINLA, threshStatMCCUpdatedINLA,
  "threshStatMCCOriginalVsUpdatedINLA.tsv", metrics = c("plr","mcc") )

# Prevalence, original vs updated, MCMC
create_model_comparison_table( threshStatPrevGlasgowMCMC, threshStatPrevUpdatedMCMC,
  "threshStatPrevOriginalVsUpdatedMCMC.tsv", metrics = c("plr","mcc") )

# Prevalence, original vs updated, INLA
create_model_comparison_table( threshStatPrevGlasgowINLA, threshStatPrevUpdatedINLA,
  "threshStatPrevOriginalVsUpdatedINLA.tsv", metrics = c("plr","mcc") )


########### Effect consistency plots ###################################################################

# These commented-out versions are not really OK because distHdg is biased by having few gardens with variance
# (because we imputed the furthest distance when no hedge is in the garden)

#plot_effect_consistency(modUpdatedDay5FinalOffset, plot_file_name = "eff_reliability_plot_updated_bars.png", credible_level=.90, display_method = "error_bars" )
#plot_effect_consistency(modGlasgowFinalOffset, plot_file_name = "eff_reliability_plot_glasgow_bars.png", credible_level=.90, display_method = "error_bars" )

plot_effect_consistency(modUpdatedDay5FinalOffset, data = dFBothFinalOffset,
                        plot_file_name = "eff_reliability_plot_updated_bars.png",
                        credible_level=.90, display_method = "error_bars", use_empirical_sds=TRUE )
slope_var_updated <- compare_random_slope_variability( modUpdatedDay5FinalOffset, dFBothFinalOffset, pred_names )
print(slope_var_updated$summary)


plot_effect_consistency(modGlasgowFinalOffset, data = dFOWithFinalOffset,
                        plot_file_name = "eff_reliability_plot_glasgow_bars.png",
                        credible_level=.90, display_method = "error_bars", use_empirical_sds=TRUE )
slope_var_glasgow <- compare_random_slope_variability( modGlasgowFinalOffset, dFOWithFinalOffset, pred_names )
print(slope_var_glasgow$summary)


######### Brier score sanity check via map plots with predictions ###################################

library(patchwork)
# Get gardens ordered by discrimination score
ord <- order(loco_results$new$decompRaws$all_data_discrimination, na.last = NA)
# Calculate duodecile positions (0, 20, 40, 60, 80, 100 percentiles)
n <- length(ord)
duodecile_positions <- round(c(0, 0.2, 0.4, 0.6, 0.8, 1.0) * (n - 1)) + 1
# Get garden IDs at each duodecile
duodecile_gardens <- loco_results$new$decompRaws$garden[ord[duodecile_positions]]
duodecile_scores <- loco_results$new$decompRaws$all_data_discrimination[ord[duodecile_positions]]
# Display the selected gardens and their scores
figure_data <- data.frame(
  percentile = c("0th (min)", "20th", "40th", "60th", "80th", "100th (max)"),
  garden = duodecile_gardens,
  discrimination_score = duodecile_scores
)
figure_data

plot_map_figure(figure_data)

############ Summarising other in-app behaviours

# Read in the CSV file
in_app <- read.csv("../additionalData/in_app_behaviour.csv",
                   fileEncoding = "UTF-8",
                   stringsAsFactors = FALSE)

# Calculate % true for the boolean columns
boolean_cols <- c("any_map_edits_in_planning", #  Entered planning mode and made edits
                  "any_model_either", # Ran any model
                  "any_model_either_impact", # Ran any model while in planning mode
                  "any_button_human", # Ran carbon model
                  "any_button_sparrow") # Ran sparrow model

# Calculate percentages
sapply(in_app[, boolean_cols], function(x) {
  mean(x, na.rm = TRUE) * 100
})

############ Demographics summary

# Note to self from author: participant_demographics.csv is generated by
# ANON_PATH\Data\user trait correlation and experimental analyses\process.R

demographics <- read.csv("../additionalData/participant_demographics.csv",
                   fileEncoding = "UTF-8",
                   stringsAsFactors = FALSE)

degree_levels <- c("Doctorate degree (PhD/other)",
                "Graduate degree (MA/MSc/MPhil/other)",
                "Undergraduate degree (BA/BSc/other)")

# Age statistics
age_median <- median(demographics$Age, na.rm = TRUE)
age_q1 <- quantile(demographics$Age, 0.25, na.rm = TRUE)
age_q3 <- quantile(demographics$Age, 0.75, na.rm = TRUE)

# Percentages
pct_female <- mean(demographics$Sex == "Female", na.rm = TRUE) * 100
pct_student <- mean(demographics$Student.status == "Yes", na.rm = TRUE) * 100
pct_fulltime <- mean(demographics$Employment.status == "Full-Time", na.rm = TRUE) * 100
pct_parttime <- mean(demographics$Employment.status == "Part-Time", na.rm = TRUE) * 100
pct_degree <- mean(demographics$Highest.education.level.completed %in% degree_levels, na.rm = TRUE) * 100


# Display results
{
  cat("Age - Median:", age_median,
      ", Q1:", age_q1,
      ", Q3:", age_q3, "\n")
  cat("Female:", pct_female, "%\n")
  cat("Student:", pct_student, "%\n")
  cat("Full-Time Employment:", pct_fulltime, "%\n")
  cat("Part-Time Employment:", pct_parttime, "%\n")
  cat("Bachelor's degree or higher:", pct_degree, "%\n")
}



